apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: busybox
  namespace: trial
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: busybox
            image: busybox
            imagePullPolicy: IfNotPresent
            args:
            - /bin/sh
            - -c
            - sleep 10
          restartPolicy: OnFailure
