apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: busybox
  namespace: trial
spec:
  selector:
    matchLabels:
      name: busybox
  template:
    metadata:
      labels:
        name: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        imagePullPolicy: IfNotPresent
        command:
        - top
