apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: trial
  labels:
    app: busybox
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nodeType
            operator: In
            values:
            - busyboxNode
  containers:
  - name: busybox
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ['/bin/sh', '-c', 'top']
