apiVersion: v1
kind: PersistentVolume
metadata:
  name: myvolume
  namespace: trial
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /home/vagrant/storage
    server: 11.12.13.13
