kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim
  namespace: trial
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
