apiVersion: v1
kind: Pod
metadata:
  name: busybox 
  namespace: trial
spec:
  containers:
  - name: busybox
    image: busybox
    imagePullPolicy: IfNotPresent   
    args:
    - /bin/sh
    - -c
    - sleep 60; touch /tmp/started; top
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/started
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 100
