apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: trial
spec:
  containers:
  - name: busybox
    image: busybox
    imagePullPolicy: IfNotPresent
    command:
    - top
    env:
      - name: USER
        valueFrom:
          secretKeyRef:
            name: credentials
            key: user
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: credentials
            key: password
