apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: trial 
spec:
  volumes:
  - name: mysql-credentials
    secret:
      secretName: mysql-secret
  containers:
  - name: busybox
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ['/bin/sh', '-c', 'top']
    volumeMounts:
    - name: mysql-credentials
      mountPath: /var/secrets
