apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: trial
spec:
  selector:
    matchLabels:
      app: busybox
  replicas: 1
  template:
    metadata:
      labels:
        app: busybox
    spec:
      tolerations:
      - key: "app"
        operator: "Equal"
        value: "busybox"
        effect: "NoSchedule"
      containers:
      - name: busybox
        image: busybox
        imagePullPolicy: IfNotPresent
        command:
        - top
